In [1]:
import iamend_ci as ci

Loading BokehJS ...

In [2]:
exp=ci.exp('./iamend_ci/datos/m1_347')
exp.fitmues()

                 archivo  conductividad   espesor bobina  muestras
0       Exp_347_Aire.csv           0.00  0.000000     m1      aire
1        Exp_347_M01.csv     1051184.21  0.022958     m1   347_M01
2        Exp_347_M02.csv     1118491.27  0.023400     m1   347_M02
3        Exp_347_M03.csv     1142610.84  0.022709     m1   347_M03
4        Exp_347_M04.csv     1216575.14  0.023400     m1   347_M04
5        Exp_347_M05.csv     1308978.66  0.023292     m1   347_M05
6        Exp_347_M06.csv     1371864.40  0.022150     m1   347_M06
7        Exp_347_M07.csv     1387902.82  0.023100     m1   347_M07
8        Exp_347_M08.csv     1415286.59  0.023025     m1   347_M08
9        Exp_347_M09.csv     1377247.16  0.022258     m1   347_M09
10       Exp_347_M11.csv     1432375.75  0.022430     m1   347_M11
11  Exp_347_Patron78.csv           0.00  0.000000     m1  Patron78
12  Exp_347_Patron80.csv           0.00  0.000000     m1  Patron80
Ajustando z1 effectivo
z1 = 1.1 mm


In [7]:
exp.info

archivo  conductividad   espesor bobina  muestras      mueff  \
0       Exp_347_Aire.csv           0.00  0.000000     m1      aire        NaN   
1        Exp_347_M01.csv     1051184.21  0.022958     m1   347_M01  59.108312   
2        Exp_347_M02.csv     1118491.27  0.023400     m1   347_M02  53.607504   
3        Exp_347_M03.csv     1142610.84  0.022709     m1   347_M03  47.266664   
4        Exp_347_M04.csv     1216575.14  0.023400     m1   347_M04  17.841392   
5        Exp_347_M05.csv     1308978.66  0.023292     m1   347_M05   7.592585   
6        Exp_347_M06.csv     1371864.40  0.022150     m1   347_M06   3.163659   
7        Exp_347_M07.csv     1387902.82  0.023100     m1   347_M07   2.713330   
8        Exp_347_M08.csv     1415286.59  0.023025     m1   347_M08   1.662739   
9        Exp_347_M09.csv     1377247.16  0.022258     m1   347_M09   1.589715   
10       Exp_347_M11.csv     1432375.75  0.022430     m1   347_M11   1.054879   
11  Exp_347_Patron78.csv           0.00  0.000000     m1  Patron78        NaN   
12  Exp_347_Patron80.csv           0.00  0.000000     m1  Patron80        NaN   

          R2  
0        NaN  
1   0.985397  
2   0.974790  
3   0.984895  
4   0.996368  
5   0.998162  
6   0.994713  
7   0.989405  
8   0.997445  
9   0.997746  
10  0.997211  
11       NaN  
12       NaN

In [13]:
exp.muplot('m03')

In [9]:
exp.fitfmues(3)

fiteo en N tramos


In [10]:
exp.info

archivo  conductividad   espesor bobina  muestras      mueff  \
0       Exp_347_Aire.csv           0.00  0.000000     m1      aire        NaN   
1        Exp_347_M01.csv     1051184.21  0.022958     m1   347_M01  59.108312   
2        Exp_347_M02.csv     1118491.27  0.023400     m1   347_M02  53.607504   
3        Exp_347_M03.csv     1142610.84  0.022709     m1   347_M03  47.266664   
4        Exp_347_M04.csv     1216575.14  0.023400     m1   347_M04  17.841392   
5        Exp_347_M05.csv     1308978.66  0.023292     m1   347_M05   7.592585   
6        Exp_347_M06.csv     1371864.40  0.022150     m1   347_M06   3.163659   
7        Exp_347_M07.csv     1387902.82  0.023100     m1   347_M07   2.713330   
8        Exp_347_M08.csv     1415286.59  0.023025     m1   347_M08   1.662739   
9        Exp_347_M09.csv     1377247.16  0.022258     m1   347_M09   1.589715   
10       Exp_347_M11.csv     1432375.75  0.022430     m1   347_M11   1.054879   
11  Exp_347_Patron78.csv           0.00  0.000000     m1  Patron78        NaN   
12  Exp_347_Patron80.csv           0.00  0.000000     m1  Patron80        NaN   

          R2   mu 1k-10k  mu 12k-100k  mu 125k-1000k  
0        NaN         NaN          NaN            NaN  
1   0.985397  165.735724    69.619828      53.996322  
2   0.974790  197.438645    67.224022      47.258611  
3   0.984895  109.149614    54.615139      43.019748  
4   0.996368   21.779035    18.486962      16.818388  
5   0.998162    7.445541     7.845417       7.463003  
6   0.994713    2.957116     3.406533       3.353224  
7   0.989405    2.471484     2.875543       3.348211  
8   0.997445    1.623970     1.733071       1.713139  
9   0.997746    1.549652     1.642372       1.708174  
10  0.997211    1.061461     1.047294       1.021334  
11       NaN         NaN          NaN            NaN  
12       NaN         NaN          NaN            NaN

In [14]:
exp.fmuplot('m01')

In [15]:
exp.fmuplot('m11')

In [16]:
from bokeh.io import output_notebook, curdoc  # output_file
from bokeh.plotting import figure, show
from bokeh.layouts import row, column, gridplot
import numpy as np


In [17]:
output_notebook()


Loading BokehJS ...

In [45]:
tool_list = ['box_zoom', 'reset']
altura=500
ancho=600
markers=["square",'triangle','circle','inverted_triangle']

In [49]:
muestra='m01'
muestra_name=exp.dznorm[exp.dznorm.muestra.str.contains(muestra.upper())].muestra.values[0]
fmu=exp.fmues[muestra_name]




plot1 = figure(x_axis_label='f[Hz]',y_axis_label='im(dz)/x0',height=altura,
               width=ancho, tools=tool_list,x_axis_type="log")
for n,fn in enumerate(fmu['fs']):
    x=fn
    ymeas=fmu['ymeas'][n]
    yteo=fmu['yteos'][n]
    plot1.scatter(x, ymeas,marker=markers[n],size=6,fill_alpha = 0)
    plot1.line(x=x, y=yteo, line_color="#f46d43", line_width=2, line_alpha=0.6)
show(plot1)

In [28]:
fmu['ymeas']

[array([0.10118972, 0.10089857, 0.10051273, 0.09981457, 0.09919751,
        0.09817336, 0.09725091, 0.09565024, 0.09378866, 0.09294258,
        0.09151042]),
 array([0.08908558, 0.08725625, 0.08491174, 0.08246927, 0.07962528,
        0.07627061, 0.0733562 , 0.0696977 , 0.06566357, 0.06125671]),
 array([0.05607711, 0.052376  , 0.04700426, 0.04071382, 0.03605724,
        0.02952567, 0.02270611, 0.01677428, 0.01048559, 0.004143  ])]

In [26]:
fmu['fs']

[array([ 1000.   ,  1258.925,  1584.893,  1995.262,  2511.886,  3162.278,
         3981.072,  5011.872,  6309.574,  7943.282, 10000.   ]),
 array([ 12589.25,  15848.93,  19952.62,  25118.86,  31622.78,  39810.72,
         50118.73,  63095.73,  79432.82, 100000.  ]),
 array([ 125892.5,  158489.3,  199526.2,  251188.6,  316227.8,  398107.2,
         501187.2,  630957.3,  794328.3, 1000000. ])]

In [93]:
exp1=ci.exp('./iamend_ci/datos/pp1_1010')
exp1.fitmues()

             archivo  conductividad  espesor bobina muestras
0  Exp_1010_Aire.csv            0.0  0.00000    pp1     aire
1    Exp_1010_M0.csv      3830000.0  0.06500    pp1  1010_M0
2  Exp_1010_P057.csv      3948000.0  0.14957    pp1     P057
Ajustando z1 effectivo
z1 = 1.606773662019182 mm


In [97]:
n_splits_f=3
exp1.fitfmues(n_splits_f)

fiteo en N tramos


In [98]:
exp1.info

archivo  conductividad  espesor bobina muestras      mueff  \
0  Exp_1010_Aire.csv            0.0  0.00000    pp1     aire        NaN   
1    Exp_1010_M0.csv      3830000.0  0.06500    pp1  1010_M0  89.564698   
2  Exp_1010_P057.csv      3948000.0  0.14957    pp1     P057        NaN   

         R2  
0       NaN  
1  0.988442  
2       NaN

In [100]:
for fn in range(n_splits_f):
    fo=int(exp1.fmues['1010_M0']['fs'][fn][0]/1000)
    ff=int(exp1.fmues['1010_M0']['fs'][fn][-1]/1000)
    exp1.info.loc[exp1.info.muestras=='1010_M0','mu '+str(fo)+'k-'+str(ff)+'k']=exp1.fmues['1010_M0']['mues'][fn]

In [102]:
exp1.info

archivo  conductividad  espesor bobina muestras      mueff  \
0  Exp_1010_Aire.csv            0.0  0.00000    pp1     aire        NaN   
1    Exp_1010_M0.csv      3830000.0  0.06500    pp1  1010_M0  89.564698   
2  Exp_1010_P057.csv      3948000.0  0.14957    pp1     P057        NaN   

         R2    mu 0k-1k   mu 2k-50k  mu 63k-1000k  
0       NaN         NaN         NaN           NaN  
1  0.988442  179.996371  124.081289     75.875761  
2       NaN         NaN         NaN           NaN

In [42]:
for x in exp.fmues.keys():
    print(x)

1010_M0


In [35]:
exp2=ci.exp('./iamend_ci/datos/m1_1010')
exp2.fitmues()
exp2.fitplot('m0')

             archivo  conductividad  espesor bobina muestras
0  Exp_1010_Aire.csv            0.0    0.000     m1     aire
1    Exp_1010_M0.csv      3830000.0    0.065     m1  1010_M0
Ajustando z1 effectivo
No se encuentra medicion sobre el patron, defina z1eff manualmente
No existe la muestra, revise .info
